#pragma checksum "C:\Projects\MvcMMF1979\Core21\Views\PrecompiledSample.cs" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8e57b80be1dd9d8c96490d678627246649e358b8"
// <auto-generated/>
#pragma warning disable 1591
//[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
//[assembly: global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Index.cshtml", typeof(AspNetCore.Views_Home_Index))]
namespace AspNetCore
{
#line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Projects\MvcMMF1979\Core21\Views\_ViewImports.cshtml"
    using Core21;

#line default
#line hidden
#line 2 "C:\Projects\MvcMMF1979\Core21\Views\_ViewImports.cshtml"
    using Core21.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"8e57b80be1dd9d8c96490d678627246649e358b8", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"6ea21b73eae9c40913aca2fd489503bdf50112b9", @"/Views/_ViewImports.cshtml")]
    public class PrecompiledSample : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Article>
    {
#pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(16, 33, true);
            WriteLiteral("[Index.cshtml start]\r\n<br />\r\n<b>");
            EndContext();
            BeginContext(50, 11, false);
#line 4 "C:\Projects\MvcMMF1979\Core21\Views\PrecompiledSample.cs"
            Write(Model.Title);
#line default
#line hidden
            EndContext();
            BeginContext(61, 14, true);
            WriteLiteral("</b>\r\n<br />\r\n");
            EndContext();
            BeginContext(76, 10, false);
#line 6 "C:\Projects\MvcMMF1979\Core21\Views\PrecompiledSample.cs"
            Write(Model.Text);

#line default
#line hidden
            EndContext();
            BeginContext(86, 38, true);
            WriteLiteral("\r\n<br />\r\n[Index.cshtml end]\r\n<br />\r\n");
            EndContext();
        }
#pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Article> Html { get; private set; }
    }
}
#pragma warning restore 1591
