#pragma checksum "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "65097d0df6947fe255aecd764111eb9f786a7b76"
// <auto-generated/>
#pragma warning disable 1591
//[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.PrecompiledSampleLayout), @"mvc.1.0.view", @"/Views/Shared/_Layout.cshtml")]
namespace AspNetCore
{
#line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Projects\MvcMMF1979\Core31\Views\_ViewImports.cshtml"
    using Core31;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Projects\MvcMMF1979\Core31\Views\_ViewImports.cshtml"
    using Core31.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"65097d0df6947fe255aecd764111eb9f786a7b76", @"/Views/Shared/_Layout.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e105f92da34e951588e361ad211a24e34c6766a8", @"/Views/_ViewImports.cshtml")]
    public class PrecompiledSampleLayout : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
#line hidden
#pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
#pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
#pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
#pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
#pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "65097d0df6947fe255aecd764111eb9f786a7b763174", async () => {
                WriteLiteral("\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>");
#nullable restore
#line 6 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                Write(ViewBag.Title);

#line default
#line hidden
#nullable disable
                WriteLiteral(" - My ASP.NET Application</title>\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");

            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "65097d0df6947fe255aecd764111eb9f786a7b764506", async () => {
                WriteLiteral("\r\n    [_Layout.cshtml start]<br />\r\n    LayoutVievBag: ");
#nullable restore
#line 10 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                Write(ViewBag.Value);

#line default
#line hidden
#nullable disable
                WriteLiteral("<br />\r\n    ");
#nullable restore
#line 11 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                Write(RenderBody());

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    <div>\r\n");
#nullable restore
#line 13 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                foreach (var i in new[] { 1, 2, 3 })
                {

#line default
#line hidden
#nullable disable
                    WriteLiteral("            <span>");
#nullable restore
#line 15 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                    Write(i);

#line default
#line hidden
#nullable disable
                    WriteLiteral("&nbsp;</span>\r\n");
#nullable restore
#line 16 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                }

#line default
#line hidden
#nullable disable
                WriteLiteral("   </div>\r\n    ");
#nullable restore
#line 18 "C:\Projects\MvcMMF1979\Core31\Views\Shared\_Layout.cshtml"
                Write(await Html.PartialAsync("_PartialAsync"));

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n   [_Layout.cshtml end]<br />\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n</html>\r\n");
        }
#pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
