#pragma checksum "C:\Projects\MvcMMF1979\Core31\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f62c754664fb0f1c00217025fe5c495b263cf1d0"
// <auto-generated/>
#pragma warning disable 1591
//[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.PrecompiledSample), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCore
{
#line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Projects\MvcMMF1979\Core31\Views\_ViewImports.cshtml"
    using Core31;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Projects\MvcMMF1979\Core31\Views\_ViewImports.cshtml"
    using Core31.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f62c754664fb0f1c00217025fe5c495b263cf1d0", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e105f92da34e951588e361ad211a24e34c6766a8", @"/Views/_ViewImports.cshtml")]
    public class PrecompiledSample : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Article>
    {
#pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("[Index.cshtml start]\r\n<br />\r\n<b>");
#nullable restore
#line 4 "C:\Projects\MvcMMF1979\Core31\Views\Home\Index.cshtml"
            Write(Model.Title);

#line default
#line hidden
#nullable disable
            WriteLiteral("</b>\r\n<br />\r\nLorem ");
#nullable restore
#line 6 "C:\Projects\MvcMMF1979\Core31\Views\Home\Index.cshtml"
            Write(Model.Text);

#line default
#line hidden
#nullable disable
            WriteLiteral(" Ipsum\r\n<br />\r\n[Index.cshtml end]\r\n<br />\r\n");
        }
#pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Article> Html { get; private set; }
    }
}
#pragma warning restore 1591
